# Generated by Django 4.2.1 on 2023-06-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_order_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
